const constants = {
    GET_MOVIES_REQUEST      : 'GET_MOVIES_REQUEST',
    GET_MOVIES_SUCCESS      : 'GET_MOVIES_SUCCESS',
    
    GET_MORE_MOVIES         : 'GET_MORE_MOVIES',
    GET_MORE_MOVIES_SUCCESS : 'GET_MORE_MOVIES_SUCCESS',
    MOVIE_SELECTED          : 'MOVIE_SELECTED',

    GET_MOVIE_REQUEST       : 'GET_MOVIE_REQUEST',
    GET_MOVIE_SUCCESS       : 'GET_MOVIE_SUCCESS',
    
    BOOK_MOVIE              : 'BOOK_MOVIE',
};

export default constants;